#!/bin/bash
$HOME/.screenlayout/default.sh
#dunst &
#compton &
#feh --bg-scale $HOME/.background.png
$HOME/bin/polystart
#plank &
megasync &
thunderbird &
slack -u &
gtk-launch signal-tray &
$HOME/clear_vim
nm-applet &
bidtray &
