#! /bin/sh

sxhkd &

HOSTNAME=`hostname`

if [ $HOSTNAME == "desktop" ]; then
    bspc monitor HDMI-A-1 -n L
    bspc monitor L -d 1 2 3 4
    bspc monitor HDMI-A-0 -n R
    bspc monitor R -d Q W E R
elif [ $HOSTNAME == "xps" ]; then
	bspc monitor eDP1 -n P
	bspc monitor P -d 1 2 3 4 Q W E R
	bspc monitor HDMI-0 -n S
	bspc monitor S -d 5 6
fi


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#aaaaaa"
bspc config normal_border_color "#333333"

bspc config presel_feedback_color "#aaaaaa"
