#! /bin/sh

bspc rule -a lattedock layer=above

sxhkd &

HOSTNAME=`hostname`

if [ $(hostname) == "desktop" ]; then
    bspc monitor HDMI-A-0 -n R
    bspc monitor HDMI-A-1 -n L
    bspc monitor L -d 1 2 3 4
    bspc monitor R -d 5 6 7 8
	echo 2 > /home/miltfra/.desktops
elif [ $(hostname) == "xps" ]; then
	bspc monitor eDP1 -n P
	bspc monitor P -d 1 2 3 4 Q W E R
	bspc monitor HDMI-0 -n S
	bspc monitor S -d 5 6
fi


bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#777777"
bspc config normal_border_color "#333333"

bspc config presel_feedback_color "#aaaaaa"

bspc rule -a Zathura state=tiled
bspc rule -a plasmashell state=floating
bspc rule -a lattedock state=floating
bspc rule -a latte-dock border=off layer=below state=floating manage=off
bspc rule -a polybar layer=above

# Left Monitor
bpsc rule -a firefox desktop=L:^1
bspc rule -a TelegramDesktop desktop=L:^3
bspc rule -a Thunderbird desktop=L:^3
bspc rule -a "Signal Beta" desktop=L:^3
bspc rule -a spotify desktop=L:^4
bspc rule -a discord desktop=L:^4
bspc rule -a "TeamSpeak 3" desktop=L:^4

# Right Monitor
bspc rule -a Lutris desktop=R:^4
bspc rule -a Wine state=pseudo_tiled border=off desktop=R:^3
bspc rule -a Code desktop=R:^1
